// <auto-generated />
namespace OutLesson.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeddescriptioninpostandofferpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeddescriptioninpostandofferpost));
        
        string IMigrationMetadata.Id
        {
            get { return "201709031626076_Added description in post and offerpost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
